### ISSUE TITLE
Grammarly

### ISSUE THREAD

**Issue by alexstrat** [getstation/electron-chrome-extension#11]
_Extension id: `kbfnbcaeplbcioakkpcpgfkobkghlhen`_
[Chrome Webstore](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en)

**Comment by hugomano** [comment]
see https://github.com/electron/electron/issues/17069

**Comment by splintor** [comment]
@hugomano Now that #42 is merged, can you give details about the current status of Grammarly extension support in Station? Thanks! 🙏

**Comment by thoraxe** [comment]
@hugomano is this closed because it's been decided this won't work?

**Comment by thoraxe** [comment]
OK, after some research I see that Grammarly as a dedicated app is available, however it doesn't seem to add the Grammarly checking to other apps (eg: GMail) like the traditional chrome extension does.

It's not clear from https://feedback.getstation.com/feature-requests/p/integrate-chrome-extensions-support-grammarly-todoist-zoom-hubspot-forgmail-simp whether or not that is planned.
