### ISSUE TITLE
Missing module '@electron/internal/browser/ipc-main-internal'

### ISSUE THREAD

**Issue by EnderDev** [getstation/electron-chrome-extension#55]
Hi there. Recently found this and decided to try it out. Ran the application and I got this error. `@electron/internal/browser/ipc-main-internal`, I then tried to `npm i` it, however got this error `Could not install from "@electron\internal\browser\ipc-main-internal" as it does not contain a package.json file.`

**Comment by magne4000** [comment]
Hi @EnderDev, what version of this package and what version of Electron are you using?

**Comment by EnderDev** [comment]
Package: `^3.0.0`, Electron: `7.0.0-nightly.20190721`

**Comment by magne4000** [comment]
We haven't tested this package with `6.x` nor `7.x` yet, there could have been some breaking changes. The currently supported version is the `5.x` branch of Electron.

**Comment by EnderDev** [comment]
Ok
